from enum import Enum


class TaskStatus(str, Enum):
    PENDENTE = "PENDENTE"
    ENVIADA = "ENVIADA"
    CONCLUIDA = "CONCLUIDA"


class DocumentType(str, Enum):
    HOLERITE = "HOLERITE"
    EXTRATO_MENSAL = "EXTRATO_MENSAL"
    DARF = "DARF"
    GUIA_FGTS = "GUIA_FGTS"
    SIMPLES_NACIONAL = "SIMPLES_NACIONAL"
    CONTRATO_SOCIAL = "CONTRATO_SOCIAL"
    BALANCETE = "BALANCETE"
    DECLARACAO_IR = "DECLARACAO_IR"
    OUTRO = "OUTRO"


class Department(str, Enum):
    RH = "RH"
    CONTABIL = "CONTABIL"
    FISCAL = "FISCAL"
    CADASTRO  = "CADASTRO"
    PARCELAMENTOS = "PARCELAMENTOS"
    DECLARACOES = "DECLARACOES"
    FINANCEIRO = "FINANCEIRO"
